name: Check For Secrets Workflow
on:
  workflow_call:
jobs:
  lint_with_black:
    name: Lint using Black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Run Black Against Code
        uses: rickstaa/action-black@v1
        id: action_black
        with:
            black_args: "."
      - name: Create Pull Request
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          title: "Black Linter Formatting Changes from psf/black check"
          commit-message: ":art: Automated Black Linting Changes"
          body: |
            There appear to be some python formatting errors in ${{ github.sha }}. This pull request
            uses the [psf/black](https://github.com/psf/black) formatter to fix these issues.
          base: ${{ github.head_ref }}
          branch: actions/black