name: Continous Delivery Workflow
on:
  workflow_call:
jobs:
  resolve_environment:
    uses: providence-wealth-systems/.github/.github/workflows/resolve_environment.yml@main
    secrets: inherit
  deploy_sam:
    uses: providence-wealth-systems/.github/.github/workflows/deploy_sam.yml@main
    secrets: inherit
    needs: resolve_environment
