name: Continous Delivery Workflow
on:
  workflow_call:
jobs:
  determine_if_sam:
    name: Determine If SAM Application
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      file_exists: ${{ steps.is_sam.outputs.files_exists }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Check If SAM Application
        id: is_sam
        uses: andstor/file-existence-action@v3
        with:
          files: 'template.yaml'
  determine_if_nextjs:
    name: Determine If Next.js Application
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      file_exists: ${{ steps.is_nextjs_app.outputs.files_exists }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Check If Next.js Application
        id: is_nextjs_app
        uses: andstor/file-existence-action@v3
        with:
          files: 'pages/assumptions.js'
  determine_if_everest:
    name: Determine If Everest FE Application
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      file_exists: ${{ steps.is_everest_app.outputs.files_exists }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Check If Everest FE Application
        id: is_everest_app
        uses: andstor/file-existence-action@v3
        with:
          files: 'pages/_app.tsx'
  determine_if_library:
    name: Determine If Library
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      file_exists: ${{ steps.is_library.outputs.files_exists }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Check If Next.js Application
        id: is_library
        uses: andstor/file-existence-action@v3
        with:
          files: 'setup.py'
  deploy_sam:
    needs: determine_if_sam
    if: needs.determine_if_sam.outputs.file_exists == 'true' && ${{ vars.IS_CONTAINERIZED_LAMBDA != 'yes' }}
    uses: providence-wealth-systems/.github/.github/workflows/deploy_sam.yml@main
    secrets: inherit
  deploy_s3:
    needs: determine_if_nextjs
    if: needs.determine_if_nextjs.outputs.file_exists == 'true'
    uses: providence-wealth-systems/.github/.github/workflows/deploy_splendid.yml@main
    secrets: inherit
  deploy_library:
    needs: determine_if_library
    if: needs.determine_if_library.outputs.file_exists == 'true'
    uses: providence-wealth-systems/.github/.github/workflows/deploy_library.yml@main
    secrets: inherit
  deploy_lambda_containerized_code:
    if: ${{ vars.IS_CONTAINERIZED_LAMBDA == 'yes' }}
    uses: providence-wealth-systems/.github/.github/workflows/deploy_lambda_container.yml@main
    secrets: inherit