name: Continuous Integration Workflow
on:
  workflow_call:
jobs:
  check_for_secrets:
    uses: providence-wealth-systems/.github/.github/workflows/secrets_check.yml@main
    secrets: inherit
  lint_code:
    uses: providence-wealth-systems/.github/.github/workflows/black_linter.yml@main
    secrets: inherit