name: Continuous Integration Workflow
on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  check_for_secrets:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    uses: providence-wealth-systems/.github/.github/workflows/secrets_check.yml@main
    secrets: inherit
  lint_code:
    uses: providence-wealth-systems/.github/.github/workflows/linter.yml@main
    needs: check_for_secrets
    secrets: inherit
  run_tests:
    uses: providence-wealth-systems/.github/.github/workflows/tests.yml@main
    needs: lint_code
    secrets: inherit
  vuln_check:
    uses: providence-wealth-systems/.github/.github/workflows/vuln_check.yml@main
    needs: run_tests
    secrets: inherit
  build_and_publish_docker:
    uses: providence-wealth-systems/.github/.github/workflows/docker.yml@main
    needs: vuln_check
    secrets: inherit
  deploy_production_artifacts:
    needs: build_and_publish_docker
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
    uses: providence-wealth-systems/.github/.github/workflows/cd.yml@main
    secrets: inherit
