name: Deploy Library To AWS Code Artifact
on:
  workflow_call:
jobs:
  determine_if_library:
    name: Determine If Library Repositry
    runs-on: ubuntu-latest
    continue-on-error: true
    if: github.ref == 'refs/heads/main'
    outputs:
      file_exists: ${{ steps.is_library.outputs.exists }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Check If Library
        id: is_library
        uses: thebinaryfelix/check-file-existence-action@main
        with:
          files: 'setup.py'
  publish_artifact:
    name: Deploy Library To AWS Code Artifact
    runs-on: ubuntu-latest
    needs: determine_if_library
    if: ${{ needs.determine_if_library.outputs.file_exists }} == 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Setup Python Envirnoment  
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build and publish
        run: |
          aws codeartifact login --tool twine --repository ${{ vars.CODEARTIFACT_SHARED_CLASS_REPOSITORY }} --domain ${{ vars.CODEARTIFACT_DOMAIN }} --domain-owner ${{ vars.CODEARTIFACT_DOMAIN_OWNER }} --region us-east-1
          python setup.py sdist
          twine upload --repository codeartifact dist/*

