name: Deploy AWS SAM Application
on:
  workflow_call:
jobs:
  deploy:
    name: Deploy To AWS
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
    environment: ${{ github.ref == 'refs/heads/main' && 'Production' || 'Staging' }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Check If Library
        id: is_aws_sam_application
        continue-on-error: true
        uses: thebinaryfelix/check-file-existence-action@main
        with:
          files: 'samconfig.toml'
      
      - name: Setup AWS SAM Credentials
        if: ${{ steps.is_aws_sam_application.outputs.exists }} == 'true'
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ github.ref == 'refs/heads/main' && secrets.AWS_ACCESS_KEY_ID_PROD || secrets.AWS_ACCESS_KEY_ID_STAGE }}
          aws-secret-access-key: ${{ github.ref == 'refs/heads/main' && secrets.AWS_SECRET_ACCESS_KEY_PROD || secrets.AWS_SECRET_ACCESS_KEY_STAGE }}
          aws-region: us-east-1

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup CodeArtifact Access Credentials
        run: aws codeartifact login --tool pip --repository ${{ vars.CODEARTIFACT_SHARED_CLASS_REPOSITORY }} --domain ${{ vars.CODEARTIFACT_DOMAIN}} --domain-owner ${{ vars.CODEARTIFACT_DOMAIN_OWNER }} --region us-east-1

      - name: Build AWS SAM Application
        run: sam build -m requirements.txt
      
      - name: Deploy AWS SAM Application
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
