name: Build & Publish Docker Image
on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  create_container_version:
    runs-on: ubuntu-latest
    env: 
      REPO_NAME: "${{ github.event.repository.name }}"
    outputs:
      CONTAINER_NAME: ${{ steps.final_output.outputs.CONTAINER_NAME }}
    steps:
      - uses: actions/checkout@v3
        with:
            token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Get Application Version from app/config_default.yaml
        run: echo """VERSION=$(grep 'BUILD_VERSION' app/config_default.yaml | cut -d '"' -f 2)""" >> $GITHUB_ENV
      - name: Set Repo Name To Lowercase
        run: echo REPO_NAME_LOWER_CASE="${REPO_NAME,,}" >> $GITHUB_ENV
      - name: Check if not main branch
        if: ${{ github.ref }} != 'refs/heads/main'
        run: echo CONTAINER_NAME="$REPO_NAME_LOWER_CASE":"$VERSION"-${{ github.sha }} >> $GITHUB_ENV
      - name: Check if main branch
        if: ${{ github.ref }} == 'refs/heads/main'
        run: echo CONTAINER_NAME="$REPO_NAME_LOWER_CASE":"$VERSION" >> $GITHUB_ENV
      - name: Set Final Container Name
        id: final_output
        run: echo CONTAINER_NAME="$CONTAINER_NAME" >> $GITHUB_OUTPUT
  build_and_publish_container:
    name: Build & Publish Dockerfile  
    needs: [create_container_version]
    runs-on: ubuntu-latest
    env:
      CONTAINER_NAME: ${{ needs.create_container_version.outputs.CONTAINER_NAME }}
    steps:
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: actions/checkout@v3
        with:
            token: ${{ secrets.WORKFLOW_TOKEN }}
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - run: echo CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain ${{ vars.CODEARTIFACT_DOMAIN}} --domain-owner ${{ vars.CODEARTIFACT_DOMAIN_OWNER }} --query authorizationToken --output text --region us-east-1 ) >> $GITHUB_ENV
      - run: echo PIP_INDEX_URL="https://aws:$CODEARTIFACT_AUTH_TOKEN@${{ vars.CODEARTIFACT_DOMAIN }}-${{ vars.CODEARTIFACT_DOMAIN_OWNER }}.d.codeartifact.us-east-1.amazonaws.com/pypi/${{ vars.CODEARTIFACT_SHARED_CLASS_REPOSITORY }}/simple/" >> $GITHUB_ENV
      - name: Build Container Image
        run: docker build -t providencewealth/"$CONTAINER_NAME" --build-arg PIP_INDEX_URL="$PIP_INDEX_URL" .
      - name: Publish Container Image
        run: docker push providencewealth/"$CONTAINER_NAME"