name: Resolve Deployment Environmnet
on:
  workflow_call:
jobs:
  resolve_environment:
    name: Figure out deployment environmnet
    runs-on: ubuntu-latest
    outputs:
        ENVIRONMENT: ${{ steps.set_environment.outputs.ENVIRONMENT }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Environment
        id: set_environment
        run: |
            if [[ $GITHUB_REF == 'refs/head/main' ]]; then
                echo ENVIRONMENT=Production >> $GITHUB_OUTPUT
            fi
            if [[ $GITHUB_REF == 'refs/head/staging' ]]; then
                echo ENVIRONMENT=Staging >> $GITHUB_OUTPUT
            fi
      - name: What is Environment?
        run: echo "${{ steps.set_environment.outputs.ENVIRONMENT }}"