name: Check For Secrets Workflow
on:
  workflow_call:
jobs:
  # ibm_detect_secrets_check:
  #   name: Run IBM Detect-Secrets
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v4
  #       with:
  #         token: ${{ secrets.WORKFLOW_TOKEN }}
  #     - name: IBM Detect Secrets scanner
  #       uses: bigpick/ibm-detect-secrets-action@0.0.1
  #       with:
  #         python_version: '3.9.13'
  #         detect_secret_additional_args: '--exclude-files .github/* --use-all-plugins --no-base64-string-scan'
  trivy_secret_check:
    name: Run AquaSecurity Trivy Scan On Files (Secrets)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Run Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scanners: 'secret'
          github-pat: ${{ secrets.WORKFLOW_TOKEN }}
