name: Check For Secrets Workflow
on:
  workflow_call:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  yelp_detect_secrets_check:
    name: Run Yelp Detect-Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Scan For Secrets
        uses: secret-scanner/action@0.0.2
  trivy_secret_check:
    name: Run AquaSecurity Trivy Scan On Files (Secrets)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Run Trivy Vulnerability Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scanners: 'secret'
          github-pat: ${{ secrets.WORKFLOW_TOKEN }}